[package]
name = "cover"
version = "0.0.1"
edition = "2018"
authors = ["Fleek Team <support@fleek.co>"]

[dependencies]
serde = "1.0.132"
chrono = "0.4.19"
candid = "0.7.14"
ic-cdk = "0.5.2"
ic-cdk-macros = "0.5.2"
