name: "Data for Cover"
description: "Collect Snapshot Data for Cover Canister"

inputs:
  canister_id:
    description: "Id of the canister"
    required: true
  wasm_path:
    description: "Path to the generated wasm file"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Collecting Cover Data"
      shell: bash
      run: |
        ls -la
        echo "-------------------"
        source ${{ github.action_path}}/utils.sh
        export JSON_PATH=output.json
        jset created_at $(timestamp)
        jset canister_id ${{ inputs.canister_id }}
        jset git_ref $GITHUB_REF
        jset git_checksum $GITHUB_SHA
        jset source_snapshot_url "N/A"
        jset wasm_path ${{ inputs.wasm_path }}
        jset wasm_checksum $(wasm_checksum ${{ inputs.wasm_path }})
        jset build_log_url "TODO"

    - name: "Call Cover Lambda Service"
      shell: bash
      run: |
        source ${{ github.action_path}}/utils.sh
        verifyDependency COVER_SQS_URL
        echo "Sending to ${{env.COVER_SQS_URL}} <-"
        jq < "${{ github.workspace }}/output.json"
        curl -X POST ${{env.COVER_SQS_URL}} -H "Content-Type: application/json" -d "@output.json"
