name: "Data for Cover"
description: "Collect Snapshot Data for Cover Canister"

inputs:
  canister_id:
    description: "Id of the canister"
    required: true
  wasm_path:
    description: "Path to the generated wasm file"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Collecting Cover Data"
      shell: bash
      run: |
        source ${{ github.action_path}}/sctipts/utils.sh
        export JSON_PATH=output.json
        jset github_job ${{ job.run_id }}
        jset created_at $(timestamp)
        jset canister_id ${{ inputs.canister_id }}
        jset git_ref $GITHUB_REF
        jset git_sha $GITHUB_SHA
        jset git_repo $GITHUB_REPOSITORY
        jset wasm_path ${{ inputs.wasm_path }}
        jset wasm_checksum $(wasm_checksum ${{ inputs.wasm_path }})
        jset build_log_url "NA"
        jset source_snapshot_url "NA"

    - name: "Call Cover SQS Lambda"
      shell: bash
      run: |
        # Set URL of the Lambda receiving SQS cover events
        export COVER_LAMBDA_URL="https://7d6er3977d.execute-api.us-west-2.amazonaws.com/dev/publishSqs"
        jq < "${{ github.workspace }}/output.json"
        ret=$(curl -i -X POST ${COVER_LAMBDA_URL} \
          -H "Content-Type: application/json"\
          -H "Authorized: ${{github.token}}" \
          -d "@output.json")
        echo "Sent to ${COVER_LAMBDA_URL} ${ret}"
