name: Cover build.js

on:
  push:
    branches:
      - production
      - main
      - fix/*

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: fleek/f3o:0.2.2
    env:
      cover_canister_id: "iftvq-niaaa-aaaai-qasga-cai"

    steps:
      - uses: actions/checkout@v2

#      - name: Build WASM
#        run: |
#          # HACK: set HOME to get github actions to execute correctly
#          export HOME=/root
#          export PATH="$HOME/.cargo/bin:${PATH}"
#          # Start build
#          yarn
#          MODE=PRODUCTION dfx build cover --check

      - name: Cover Validator Plugin
        uses: ./GithubActionPlugin
#        uses: Psychedelic/cover/GithubActionPlugin@main
        with:
          canister_id: ${{ env.cover_canister_id }}
          wasm_path: ".dfx/local/canisters/cover/cover.wasm"
