on:
  workflow_run:
    workflows: ["build"]
    types: [completed] #requested

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo "First workflow was a success"

      - name: Cover Validator Plugin
        uses: ./GithubActionPlugin
        #        uses: Psychedelic/cover/GithubActionPlugin@main
        with:
          canister_id: ${{ env.cover_canister_id }}  # some random ic
          wasm_path: ".dfx/local/services/cover.wasm"

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo "First workflow was a failure"
