name: Cover build

on:
  workflow_dispatch:
    inputs:
      owner_id:
        description: 'Owner id'
        required: true
        type: string
      canister_id:
        description: 'Canister id'
        required: true
        type: string
      canister_name:
        description: 'Canister name'
        required: true
        type: string
      repo_url:
        description: 'Repo url'
        required: true
        type: string
      repo_access_token:
        description: 'Repo access token'
        required: true
        type: string
      commit_hash:
        description: 'Repo commit hash'
        required: true
        type: string
      rust_version:
        description: 'Rust version'
        required: false
        type: string
      dfx_version:
        description: 'DFX version'
        required: true
        type: string
      optimize_count:
        description: 'Optimize count'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    container: namdh2604/cover
    steps:
      - name: Clone github repo
        run: |
          git init
          git remote add origin https://${{ github.event.inputs.repo_access_token }}@${{ github.event.inputs.repo_url }}
          git fetch origin ${{ github.event.inputs.commit_hash }} --depth 1
          git reset --hard FETCH_HEAD
      - name: Validate dfx build type
        run: |
          case  $(jq '.canisters.${{ github.event.inputs.canister_name }}.type' < dfx.json) in 
            (\"rust\" | \"motoko\") 
              echo "Passed" 
              ;;
            (*) 
              echo "Only support DFX build type \"rust\" or \"motoko\""
              exit 1
              ;;
          esac
      - name: Cache Rust
        id: cache-rust
        uses: actions/cache@v2
        with:
          path: |
            /opt/cargo/bin/
            /opt/cargo/registry/index/
            /opt/cargo/registry/cache/
            /opt/cargo/git/db/
            /opt/rustup/
            target/
          key: Ubuntu-cargo-${{ hashFiles('**/Cargo.lock') }}-version-${{ github.event.inputs.rust_version }}
      - name: Cache DFX
        id: cache-dfx
        uses: actions/cache@v2
        with:
          path: /usr/local/bin/dfx
          key: Ubuntu-dfx-version-${{ github.event.inputs.dfx_version }}
      - name: Setup env
        if: github.event.inputs.rust_version != ''
        run: |
          echo "RUSTUP_HOME=/opt/rustup" >> $GITHUB_ENV
          echo "CARGO_HOME=/opt/cargo" >> $GITHUB_ENV
          echo "PATH=/opt/cargo/bin:$PATH" >> $GITHUB_ENV
      - name: Install Rust toolchain
        if: github.event.inputs.rust_version != '' && steps.cache-rust.outputs.cache-hit != 'true'
        env:
          RUST_VERSION: ${{ github.event.inputs.rust_version }}
        run: |
          echo "No Rust found. Start downloading..."
          curl --fail https://sh.rustup.rs/ -sSf | sh -s -- -y --default-toolchain ${RUST_VERSION}-x86_64-unknown-linux-gnu --no-modify-path
          rustup default ${RUST_VERSION}-x86_64-unknown-linux-gnu
          rustup target add wasm32-unknown-unknown
      - name: Install DFX
        if: steps.cache-dfx.outputs.cache-hit != 'true'
        env:
          DFX_VERSION: ${{ github.event.inputs.dfx_version }}
        run: |
          echo "No DFX found. Start downloading..."
          curl -fsSL https://sdk.dfinity.org/install.sh | bash
      - name: Install optimizer
        if: github.event.inputs.rust_version != '' && steps.cache-rust.outputs.cache-hit != 'true'
        run: cargo install ic-cdk-optimizer --vers 0.3.3
      - name: Build wasm
        run: dfx build --network ic ${{ github.event.inputs.canister_name }}
      - name: Optimize wasm
        if: github.event.inputs.optimize_count > 0 && github.event.inputs.rust_version != ''
        run: |
          i=0
          while [ $i -lt ${{ github.event.inputs.optimize_count }} ]
          do
            ic-cdk-optimizer .dfx/ic/canisters/${{ github.event.inputs.canister_name }}/${{ github.event.inputs.canister_name }}.wasm \
            -o .dfx/ic/canisters/${{ github.event.inputs.canister_name }}/${{ github.event.inputs.canister_name }}.wasm
            i=`expr $i + 1`
          done
      - name: Hash wasm
        run: |
          echo "WASM_HASH=$(openssl dgst -sha256 .dfx/ic/canisters/${{ github.event.inputs.canister_name }} \
          /${{ github.event.inputs.canister_name }}.wasm | awk '/.+$/{print "0x"$2}')" >> $GITHUB_ENV
      - name: Update verification
        if: always()
        run: |
          if ! type dfx > /dev/null 
          then
           rm dfx.json
           echo "No DFX found. Start downloading..."
           DFX_VERSION="" sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"
          fi
          hash=opt\"$WASM_HASH\"
          if [ -z "$WASM_HASH" ]
          then 
            status="variant{ Error }"
          else 
            status="variant{ Success }"
          fi
          dfx canister --network ic call 3x7en-uqaaa-aaaai-abgca-cai submitVerification  \
          "(record{owner_id=principal\"${{ github.event.inputs.owner_id }}\"; \
          canister_id=principal\"${{ github.event.inputs.canister_id }}\";canister_name=\"${{ github.event.inputs.canister_name }}\"; \
          repo_url=\"${{ github.event.inputs.repo_url }}\";commit_hash=\"${{ github.event.inputs.commit_hash }}\"; \
          wasm_hash=$hash;build_url=\"https://github.com/Psychedelic/cover/actions/runs/${{github.run_id}}\";build_status=$status; \
          rust_version=opt\"${{ github.event.inputs.rust_version }}\"; dfx_version=\"${{ github.event.inputs.dfx_version }}\"; \
          optimize_count=${{ github.event.inputs.optimize_count }}:nat8})"



