name: PR Test runner (Services)

on:
  pull_request:
    branches: [ develop ]
    paths:
      - services/**
      - packages/services-test-runner/**

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FA_NPM_TOKEN: ${{secrets.FA_NPM_TOKEN}}
      PSYCHEDELIC_NPM_TOKEN: ${{secrets.PSYCHEDELIC_NPM_TOKEN}}
      PAT: ${{ secrets.PAT }}

    steps:
      - uses: actions/checkout@v2

      - name: Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
          target: wasm32-unknown-unknown

      - name: NPM Registry token setup
        run: ./.scripts/npm-registry-token-setup.sh
        env:
          PAT: ${{ secrets.PAT }}

      - name: Cache node modules
        id: node-modules-cache
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: yarn bootstrap

      - name: DFX Tooling
        run: ./.scripts/dfx-tooling.sh
        env:
          DFX_VERSION: 0.8.0
          DFX_CANDID_RELEASE: 2021-08-20

      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true

      - name: DFX Services
        run: ./.scripts/dfx-services.sh

      - name: Services unit-tests
        run: cargo test -- --show-output

      - name: Services functional tests
        run: yarn test:services
