name: Security Audit
on:
  schedule:
    - cron: "0 8 * * *"
#  pull_request:
#    branches: [ main ]
#    paths:
#      - 'Cargo.*'

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}