name: Deploy BE

on:
  push:
    branches:
      - 'staging'
      - 'production'
      - 'feat/DeployBE' # TODO: remove after tests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
          target: wasm32-unknown-unknown

      - name: NPM Registry token setup
        run: ./.scripts/npm-registry-token-setup.sh
        env:
          PAT: ${{ secrets.PAT }}

      - name: DFX Tooling
        run: ./.scripts/dfx-tooling.sh
        env:
          DFX_VERSION: 0.8.0
          DFX_CANDID_RELEASE: 2021-08-20

      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true

      - name: DFX deploy
        run: ./.scripts/setup-be.sh
        env:
          DFX_NETWORK: ic
          PAT: ${{ secrets.PAT }}
          DFX_IDENTITY: ${{ secrets.DFX_IDENTITY }}
          DFX_IDENTITY_DEVELOPMENT: ${{ secrets.DFX_IDENTITY_DEVELOPMENT }}
          DFX_IDENTITY_STAGING: ${{ secrets.DFX_IDENTITY_STAGING }}
          DFX_IDENTITY_PRODUCTION: ${{ secrets.DFX_IDENTITY_PRODUCTION }}
          DFX_WALLETS: ${{ secrets.DFX_WALLETS }}
          DFX_WALLETS_DEVELOPMENT: ${{ secrets.DFX_WALLETS_DEVELOPMENT }}
          DFX_WALLETS_STAGING: ${{ secrets.DFX_WALLETS_STAGING }}
          DFX_WALLETS_PRODUCTION: ${{ secrets.DFX_WALLETS_PRODUCTION }}
          CANISTERIUM_CANISTER_ID_DEVELOPMENT: ${{ secrets.CANISTERIUM_ID_DEVELOPMENT }}
          CANISTERIUM_CANISTER_ID_STAGING: ${{ secrets.CANISTERIUM_ID_STAGING }}
          CANISTERIUM_CANISTER_ID_PRODUCTION: ${{ secrets.CANISTERIUM_ID_PRODUCTION }}
