name: Example Rust Build

on:
  push:
    branches:
      - 'staging'
      - 'production'
      - 'feat/DeployBE' # TODO: remove after tests

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        shell: bash
        run: |
          echo "[------------------------- Executing build script --------------------------]"
      - name: Cover Validator Plugin
        uses: ./.github/actions/CoverValidator
#        uses: Psychedelic/cover/.github/actions/CoverValidator@feat/github-plugin
        with:
#          canister_id: "4n3qe-piaaa-aaaab-qac7a-cai" # some random ic
          wasm_path: "services/cover/Cargo.toml"
